#!/usr/bin/env python3
"""
Generate audio files for missing v1 syllables only.

Reads missing_audio_v1.json (generated by compare_v1_with_existing_audio.py)
and generates only the syllables that don't have audio files yet.

This is much faster than regenerating all 1,548 syllables.

Prerequisites:
1. Install boto3: pip install boto3
2. Configure AWS credentials: aws configure
3. Run compare_v1_with_existing_audio.py first

Usage:
    python scripts/audio/generate_audio_v1_missing.py

    # Or with test mode (generate first 5 only):
    python scripts/audio/generate_audio_v1_missing.py --test
"""

import os
import sys
import json
import time
import argparse
from pathlib import Path

try:
    import boto3
    from botocore.exceptions import BotoCoreError, ClientError, NoCredentialsError
except ImportError:
    print("ERROR: boto3 not installed")
    print("Install with: pip install boto3")
    sys.exit(1)


# ============================================================================
# CONFIGURATION
# ============================================================================

# AWS Configuration
AWS_REGION = os.getenv('AWS_DEFAULT_REGION', 'us-east-1')
VOICE_ID = 'Zhiyu'  # Mandarin Chinese female voice
ENGINE = 'neural'   # 'neural' (better quality) or 'standard'
OUTPUT_FORMAT = 'ogg_vorbis'  # OGG Vorbis

# Paths
PROJECT_ROOT = Path(__file__).parent.parent.parent
MISSING_JSON = PROJECT_ROOT / 'data' / 'audio' / 'missing_audio_v1.json'
OUTPUT_DIR = PROJECT_ROOT / 'app' / 'public' / 'data' / 'audio'

# Generation settings
RATE_LIMIT_DELAY = 0.15  # seconds between requests (avoid throttling)


# ============================================================================
# SSML GENERATION
# ============================================================================

def generate_ssml(syllable: str) -> str:
    """
    Generate SSML for a syllable using AWS Polly x-amazon-pinyin.

    Args:
        syllable: tone3 format (e.g., 'ma1', 'de0', 'lv3', 'ê1')

    Returns:
        SSML string with phoneme tag
    """
    # Use placeholder Chinese character
    placeholder = "字"

    # AWS Polly x-amazon-pinyin format
    # Note: Special syllables like 'ê1' might not work - we'll handle errors
    ssml = f"""<speak>
    <phoneme alphabet="x-amazon-pinyin" ph="{syllable}">{placeholder}</phoneme>
</speak>"""

    return ssml


# ============================================================================
# AWS POLLY SYNTHESIS
# ============================================================================

def synthesize_syllable(syllable: str, polly_client, output_path: Path) -> dict:
    """
    Synthesize a single syllable using AWS Polly.

    Returns:
        dict with: status, file_size, error (if any)
    """
    try:
        # Generate SSML
        ssml = generate_ssml(syllable)

        # Call AWS Polly
        response = polly_client.synthesize_speech(
            Text=ssml,
            TextType='ssml',
            OutputFormat=OUTPUT_FORMAT,
            VoiceId=VOICE_ID,
            Engine=ENGINE
        )

        # Check response
        if 'AudioStream' not in response:
            return {
                'status': 'failed',
                'file_size': 0,
                'error': 'No AudioStream in response',
                'ssml': ssml
            }

        # Read and save audio
        audio_data = response['AudioStream'].read()

        with open(output_path, 'wb') as f:
            f.write(audio_data)

        file_size = len(audio_data)

        return {
            'status': 'success',
            'file_size': file_size,
            'error': None
        }

    except (BotoCoreError, ClientError) as e:
        return {
            'status': 'failed',
            'file_size': 0,
            'error': str(e)
        }
    except Exception as e:
        return {
            'status': 'failed',
            'file_size': 0,
            'error': f'Unexpected error: {str(e)}'
        }


# ============================================================================
# MAIN GENERATION LOGIC
# ============================================================================

def main():
    # Parse arguments
    parser = argparse.ArgumentParser(description='Generate audio for missing v1 syllables')
    parser.add_argument('--test', action='store_true', help='Test mode: generate only first 5 syllables')
    args = parser.parse_args()

    print("=" * 80)
    print("Generate Audio for Missing v1 Syllables (AWS Polly)")
    print("=" * 80)

    # Load missing syllables list
    print(f"\nLoading missing syllables from: {MISSING_JSON}")

    if not MISSING_JSON.exists():
        print(f"ERROR: Missing syllables file not found!")
        print(f"Run: python scripts/audio/compare_v1_with_existing_audio.py")
        sys.exit(1)

    with open(MISSING_JSON, 'r', encoding='utf-8') as f:
        data = json.load(f)

    missing_syllables = data['missing_syllables']
    total_missing = len(missing_syllables)

    print(f"✓ Loaded {total_missing} missing syllables")

    if total_missing == 0:
        print("\n✓ No missing syllables - all v1 syllables have audio!")
        return

    # Test mode
    if args.test:
        print(f"\n⚠️  TEST MODE: Generating first 5 syllables only")
        missing_syllables = missing_syllables[:5]
        total_missing = len(missing_syllables)

    # Create output directory
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    # Initialize AWS Polly client
    print(f"\nInitializing AWS Polly client...")
    print(f"  Region: {AWS_REGION}")
    print(f"  Voice: {VOICE_ID} ({ENGINE})")
    print(f"  Format: {OUTPUT_FORMAT}")

    try:
        polly_client = boto3.client('polly', region_name=AWS_REGION)
        print("✓ AWS Polly client initialized")
    except NoCredentialsError:
        print("\nERROR: AWS credentials not configured!")
        print("Run: aws configure")
        sys.exit(1)
    except Exception as e:
        print(f"\nERROR: Failed to initialize Polly client: {e}")
        sys.exit(1)

    # Generate audio files
    print(f"\n{'='*80}")
    print(f"GENERATING AUDIO ({total_missing} files)")
    print(f"{'='*80}\n")

    results = {
        'success': [],
        'failed': [],
        'skipped': []
    }

    start_time = time.time()

    for i, syllable in enumerate(missing_syllables, 1):
        output_path = OUTPUT_DIR / f"{syllable}.ogg"

        # Check if file already exists (in case of resume)
        if output_path.exists():
            print(f"[{i}/{total_missing}] {syllable:8s} → SKIPPED (file exists)")
            results['skipped'].append(syllable)
            continue

        # Synthesize
        result = synthesize_syllable(syllable, polly_client, output_path)

        if result['status'] == 'success':
            print(f"[{i}/{total_missing}] {syllable:8s} → ✓ ({result['file_size']:,} bytes)")
            results['success'].append(syllable)
        else:
            print(f"[{i}/{total_missing}] {syllable:8s} → ✗ FAILED: {result['error']}")
            results['failed'].append({'syllable': syllable, 'error': result['error']})

        # Rate limiting (except for last item)
        if i < total_missing:
            time.sleep(RATE_LIMIT_DELAY)

    elapsed_time = time.time() - start_time

    # Summary
    print(f"\n{'='*80}")
    print("GENERATION COMPLETE")
    print(f"{'='*80}")

    print(f"\nResults:")
    print(f"  Success:  {len(results['success']):3d}")
    print(f"  Failed:   {len(results['failed']):3d}")
    print(f"  Skipped:  {len(results['skipped']):3d}")
    print(f"  Total:    {total_missing:3d}")

    print(f"\nTime: {elapsed_time:.1f} seconds ({elapsed_time/60:.1f} minutes)")

    if results['failed']:
        print(f"\n⚠️  FAILED SYLLABLES ({len(results['failed'])}):")
        for item in results['failed']:
            print(f"   {item['syllable']:8s} - {item['error']}")
        print(f"\nThese syllables may need manual attention or alternative generation.")

    # Special handling note
    failed_special = [item['syllable'] for item in results['failed'] if 'ê' in item['syllable']]
    if failed_special:
        print(f"\n⚠️  Special note on ê syllables:")
        print(f"   AWS Polly may not support Vietnamese-style romanization (ê)")
        print(f"   Consider mapping these to standard pinyin equivalents:")
        print(f"     ê1 → ei1, ê2 → ei2, ê3 → ei3, ê4 → ei4")

    print(f"\n{'='*80}")
    print(f"Output directory: {OUTPUT_DIR}")
    print(f"{'='*80}")

    if len(results['success']) == total_missing:
        print("\n✓ All syllables generated successfully!")
    elif len(results['failed']) > 0:
        print(f"\n⚠️  {len(results['failed'])} syllables failed - see above for details")

    # Save results log
    log_path = PROJECT_ROOT / 'data' / 'audio' / 'generation_log_v1_missing.json'
    with open(log_path, 'w', encoding='utf-8') as f:
        json.dump({
            'timestamp': time.strftime('%Y-%m-%d %H:%M:%S'),
            'total': total_missing,
            'success': len(results['success']),
            'failed': len(results['failed']),
            'skipped': len(results['skipped']),
            'failed_details': results['failed'],
            'elapsed_seconds': elapsed_time
        }, f, indent=2, ensure_ascii=False)

    print(f"\n✓ Log saved to: {log_path}")


if __name__ == '__main__':
    main()
